export const baskets = [
    { id: 1, img: require('./assets/BASKETS/AxiomLite.jpg'), name: "Axiom Lite" },
    { id: 2, img: require('./assets/BASKETS/AxiomProBasket.jpg'), name: "Axiom Pro Basket" },
    { id: 3, img: require('./assets/BASKETS/BlackHolePro.png'), name: "Black Hole Pro Basket" },
    { id: 4, img: require('./assets/BASKETS/DGAMachLite.jpg'), name: "DGA Mach Lite Basket" },
    { id: 5, img: require('./assets/BASKETS/DiscCatcherTraveler.jpg'), name: "Disc Catcher Traveler" },
    { id: 6, img: require('./assets/BASKETS/DynamicDiscMarksmanLiteBasket.png'), name: "Dynamic Disc Marksman Lite Basket" },
    { id: 7, img: require('./assets/BASKETS/DynamicDiscRecruitBasket.png'), name: "Dynamic Disc Recruit Basket" },
    { id: 8, img: require('./assets/BASKETS/DynamicDiscScoutBasket.jpg'), name: "Dynamic Disc Scout Basket" },
    { id: 9, img: require('./assets/BASKETS/DynamicDiscVeteranBasket.png'), name: "Dynamic Disc Veteran Basket" },
    { id: 10, img: require('./assets/BASKETS/Latitude64ProBasket.png'), name: "Latitude 64 Pro Basket" },
    { id: 11, img: require('./assets/BASKETS/Latitude64ProBasketSkill.png'), name: "Latitude 64 Pro Basket Skill" },
    { id: 12, img: require('./assets/BASKETS/SREAMLINELITE.jpg'), name: "Streamline Lite Basket" },
 ]

 export const companyNames = [
    { id: 1, name: "Disc Craft" },
    { id: 2, name: "Disc Mania" },
    { id: 3, name: "Dynamic Discs" },
    { id: 4, name: "Gateway Discs" },
    { id: 5, name: "Infinte Discs" },
    { id: 6, name: "Innova Discs" },
    { id: 7, name: "Lattitude 64 Discs" },
    { id: 8, name: "Millenium Discs" },
    { id: 9, name: "Prodigy Discs" },
    { id: 10, name: "West Side Discs" }, 
    { id: 11, name: "Legacy Discs" },
    { id: 12, name: "Kastoplast" },
    { id: 13, name: "Pro discus" },
    { id: 14, name: "DGA" },
    { id: 15, name: "Mvp and Axiom plastic" },
    { id: 16, name: "EV7discs" }
 ]


export const discs = [
    { id: 1, companyId: 1, img: require('./assets/allDiscs/discCraft/discCraftFierce.png'), name: "Disc Craft Fierce" },
    { id: 2, companyId: 1, img: require('./assets/allDiscs/discCraft/discCraftLuna.png'), name: "Disc Craft Luna" },
    { id: 3, companyId: 1, img: require('./assets/allDiscs/discCraft/discCraftRoach.png'), name: "Disc Craft Roach" },
    { id: 4, companyId: 2, img: require('./assets/allDiscs/discMania/discManiaLink.jpg'), name: "Disc Mania Link" },
    { id: 5, companyId: 2, img: require('./assets/allDiscs/discMania/discManiaLogic.jpg'), name: "Disc Mania Logic" },
    { id: 6, companyId: 2, img: require('./assets/allDiscs/discMania/discManiaP1.jpg'), name: "Disc Mania P1" },
    { id: 7, companyId: 2, img: require('./assets/allDiscs/discMania/discManiaP2.jpg'), name: "Disc Mania P2" },
    { id: 8, companyId: 2, img: require('./assets/allDiscs/discMania/discManiaSensei.jpg'), name: "Disc Mania Sensei" },
    { id: 9, companyId: 2, img: require('./assets/allDiscs/discMania/discManiaShogun.jpg'), name: "Disc Mania Shogun" },

    { id: 10, companyId: 3, img: require('./assets/allDiscs/dynamicDisc/dynamicDiscDeputy.jpg'), name: "Dynamic Disc Deputy" },
    { id: 11, companyId: 3, img: require('./assets/allDiscs/dynamicDisc/dynamicDiscJudge.jpg'), name: "Dynamic Disc Judge" },
    { id: 12, companyId: 3, img: require('./assets/allDiscs/dynamicDisc/dynamicDiscWarden.jpg'), name: "Dynamic Disc Warden" },
    { id: 13, companyId: 4, img: require('./assets/allDiscs/gatewayDisc/gatewayDiscJourney.png'), name: "Gateway Disc Journey" },
    { id: 14, companyId: 4, img: require('./assets/allDiscs/gatewayDisc/gatewayDiscWizard.png'), name: "Gateway Disc Wizard" },
    { id: 15, companyId: 5, img: require('./assets/allDiscs/infiniteDisc/infiniteDiscChort.jpg'),  name: "Infinite Disc Chort" },
    { id: 16, companyId: 5, img: require('./assets/allDiscs/infiniteDisc/infiniteDiscTomb.jpg'), name: "Infinite Disc Tomb" },
    { id: 17, companyId: 5, img: require('./assets/allDiscs/infiniteDisc/infinteDiscAlpaca.jpg'), name: "Infinite Disc Alpaca" },
    { id: 18, companyId: 6, img: require('./assets/allDiscs/innovaDisc/innovaDiscAviar.jpg'), name: "Innova Disc Aviar" },
    { id: 19, companyId: 6, img: require('./assets/allDiscs/innovaDisc/innovaDiscAviar2.jpg'), name: "Innova Disc Aviar B" },
    { id: 20, companyId: 6, img: require('./assets/allDiscs/innovaDisc/innovaDiscKcAviar.jpg'), name: "Innova Disc KC Aviar" },
    { id: 21, companyId: 6, img: require('./assets/allDiscs/innovaDisc/innovaDiscStarAnimal.jpg'), name: "Innova Disc Star Animal" },
    { id: 22, companyId: 7, img: require('./assets/allDiscs/Lattitude64Disc/lattitude64DiscDagger.jpg'), name: "Lattitude 64 Disc Dagger" },
    { id: 23, companyId: 7, img: require('./assets/allDiscs/Lattitude64Disc/lattitude64DiscFaith.jpg'), name: "Lattitude 64 Disc Faith" },
    { id: 24, companyId: 7, img: require('./assets/allDiscs/Lattitude64Disc/lattitude64DiscHope.jpg'), name: "Lattitude 64 Disc Hope" },
    { id: 25, companyId: 7, img: require('./assets/allDiscs/Lattitude64Disc/lattitude64DiscMercy.jpg'), name: "Lattitude 64 Disc Mercy" },
    { id: 26, companyId: 7, img: require('./assets/allDiscs/Lattitude64Disc/lattitude64DiscsKeystone.jpg'), name: "Lattitude 64 Disc Keystone" },
    { id: 27, companyId: 7, img: require('./assets/allDiscs/Lattitude64Disc/lattitude64DiscsPure.jpg'), name: "Lattitude 64 Disc Pure" },
    { id: 28, companyId: 8, img: require('./assets/allDiscs/milleniumDisc/milleniumDisc1.jpg'), name: "Millineum Disc Draco" },
    { id: 29, companyId: 8, img: require('./assets/allDiscs/milleniumDisc/milleniumDisc2.jpg'), name: 'Milleneum Disc Omega' },
    { id: 30, companyId: 9, img: require('./assets/allDiscs/prodigyDisc/prodigy1.png'), name: "Prodigy Disc pa-1" },
    { id: 31, companyId: 9, img: require('./assets/allDiscs/prodigyDisc/prodigy2.png'), name: "Prodigy Disc pa-model" },
    { id: 32, companyId: 9, img: require('./assets/allDiscs/prodigyDisc/prodigy3.png'), name: "Prodigy Disc pa-2" },
    { id: 33, companyId: 9, img: require('./assets/allDiscs/prodigyDisc/prodigyDiscsPA-3models.png'), name: "Prodigy Disc pa-3" },
    { id: 34, companyId: 9, img: require('./assets/allDiscs/prodigyDisc/prodidyDiscPA-4.png'), name: "Prodigy Disc pa-4" },
    { id: 35, companyId: 9, img: require('./assets/allDiscs/prodigyDisc/prodigyDiscsp-models.png'), name: "Prodigy Disc p-model" },
    { id: 36, companyId: 10, img: require('./assets/allDiscs/westsideDisc/westSideDiscCrown.png'), name: "Westside Disc Crown" },
    { id: 37, companyId: 10, img: require('./assets/allDiscs/westsideDisc/westSideDiscMaiden.png'), name: "Westside Disc Maiden" },
    { id: 38, companyId: 10, img: require('./assets/allDiscs/westsideDisc/westSideDiscSwan.png'), name: "Westside Disc Swan" },
    { id: 39, companyId: 10, img: require('./assets/allDiscs/westsideDisc/westsideDiscSwan1Reborn.jpg'), name: "Westside Disc Swan 1 Reborn" },
    { id: 40, companyId: 12, img: require('./assets/allDiscs/kastoPlastDiscs/kastplastDiscRekoX.jpg'), name: "Kastplast Disc RekoX" },
    { id: 41, companyId: 12, img: require('./assets/allDiscs/kastoPlastDiscs/kastplastDiscsReko.jpg'), name: "Kastplast Disc Reko" },
    { id: 42, companyId: 13, img: require('./assets/allDiscs/Prodiscus/proDiscusjokeri.jpg'), name: "Pro Discus Jokeri" },
    { id: 43, companyId: 13, img: require('./assets/allDiscs/Prodiscus/proDiscusSparta.jpg'), name: "Pro Discus Sparta" },
    { id: 44, companyId: 14, img: require('./assets/allDiscs/DGAdiscs/DGADiscsBlowfly.jpg'), name: "DGA Disc Blow Fly" },
    { id: 45, companyId: 14, img: require('./assets/allDiscs/DGAdiscs/DGADiscsSteady.jpg'), name: "DGA Disc Steady" },
    { id: 46, companyId: 14, img: require('./assets/allDiscs/DGAdiscs/DGADiscsSteadyBL.jpg'), name: "DGA Disc SteadyBL" },
    { id: 47, companyId: 15, img: require('./assets/allDiscs/axiomdiscs/AxiomEnvy.jpg'), name: "Axiom Disc Envy" },
    { id: 48, companyId: 15, img: require('./assets/allDiscs/axiomdiscs/AxiomProxy.jpg'), name: "Axiom Disc Proxy" },
    { id: 49, companyId: 15, img: require('./assets/allDiscs/axiomdiscs/MVPAtom.jpg'), name: "MVP Disc Atom" },
    { id: 50, companyId: 15, img: require('./assets/allDiscs/axiomdiscs/MVPNomad.jpg'), name: "MVP Disc Nomad" },
    { id: 51, companyId: 15, img: require('./assets/allDiscs/axiomdiscs/MVPOhm.jpg'), name: "MVP Disc Ohm" },
    { id: 52, companyId: 16, img: require('./assets/allDiscs/EV-7discs/EV-7Mobius.png'), name: "EV-7 Mobius" },
    { id: 53, companyId: 16, img: require('./assets/allDiscs/EV-7discs/EV-7Penrose.png'), name: "EV-7 Penrose" },
    { id: 54, companyId: 16, img: require('./assets/allDiscs/EV-7discs/EV-7Phi.png'), name: "EV-7 PHI" },

]

export const Plastics = [
    { id: 1, companyId: 1, name: "Fix" },
    { id: 2, companyId: 1, name: "Ti" },
    { id: 3, companyId: 1, name: "ESP" },
    { id: 4, companyId: 1, name: "Z" },
    { id: 5, companyId: 1, name: "Z Lite" },
    { id: 6, companyId: 1, name: "Saw breaker" },
    { id: 7, companyId: 1, name: "X" },
    { id: 8, companyId: 1, name: "Pro D" },
    { id: 9, companyId: 2, name: "D line" },
    { id: 10, companyId: 2, name: "C line" },
    { id: 11, companyId: 2, name: "X line" },
    { id: 12, companyId: 2, name: "G line" },
    { id: 13, companyId: 2, name: "Blizzard C-line" },
    { id: 14, companyId: 2, name: "Glow C-line" },
    { id: 15, companyId: 2, name: "Metal Plate" },
    { id: 16, companyId: 2, name: "Luster C-line" },
    { id: 17, companyId: 2, name: "Slimmer C-line" },
    { id: 18, companyId: 2, name: "Exo" },
    { id: 19, companyId: 2, name: "Neo" },
    { id: 20, companyId: 2, name: "Lux" },
    { id: 21, companyId: 2, name: "Forge" },
    { id: 22, companyId: 2, name: "Active" },
    { id: 23, companyId: 2, name: "Active Premium" },
    { id: 24, companyId: 2, name: "Lady Line" },
    { id: 25, companyId: 2, name: "SG Line" },
    { id: 26, companyId: 3, name: "Moonshine" },
    { id: 27, companyId: 3, name: "Lucid" },
    { id: 28, companyId: 3, name: "Lucid air" },
    { id: 29, companyId: 3, name: "Fluid" },
    { id: 30, companyId: 3, name: "Bio fusion" },
    { id: 31, companyId: 3, name: "Classic super soft" },
    { id: 32, companyId: 3, name: "Classic bend" },
    { id: 33, companyId: 3, name: "Classic" },
    { id: 34, companyId: 3, name: "Prime" },
    { id: 35, companyId: 4, name: "Organic" },
    { id: 36, companyId: 4, name: "Eraser" },
    { id: 37, companyId: 4, name: "Money" },
    { id: 38, companyId: 4, name: "Special Blend" },
    { id: 39, companyId: 4, name: "Diamond" },
    { id: 40, companyId: 4, name: "D-Glow" },
    { id: 41, companyId: 4, name: "Platinuim" },
    { id: 42, companyId: 4, name: "Pure white" },
    { id: 43, companyId: 4, name: "Firm" },
    { id: 44, companyId: 4, name: "Super soft" },
    { id: 45, companyId: 4, name: "Super stupid soft" },
    { id: 46, companyId: 4, name: "Super silky stupid soft" },
    { id: 47, companyId: 4, name: "Super glow" },
    { id: 48, companyId: 5, name: "S blend" },
    { id: 49, companyId: 5, name: "C blend" },
    { id: 50, companyId: 5, name: "G blend" },
    { id: 51, companyId: 5, name: "L blend" },
    { id: 52, companyId: 5, name: "X blend" },
    { id: 53, companyId: 5, name: "P blend" },
    { id: 54, companyId: 5, name: "D blend" },
    { id: 55, companyId: 6, name: "Star" },
    { id: 56, companyId: 6, name: "G star" },
    { id: 57, companyId: 6, name: "Champion" },
    { id: 58, companyId: 6, name: "Metal flake" },
    { id: 59, companyId: 6, name: "Blizzard Champion" },
    { id: 60, companyId: 6, name: "XT" },
    { id: 61, companyId: 6, name: "Driver Pro" },
    { id: 62, companyId: 6, name: "Kc Pro" },
    { id: 63, companyId: 6, name: "R Pro" },
    { id: 64, companyId: 6, name: "JK Pro" },
    { id: 65, companyId: 6, name: "DX" },
    { id: 66, companyId: 7, name: "Gold Line" },
    { id: 67, companyId: 7, name: "Opto" },
    { id: 68, companyId: 7, name: "Opto air" },
    { id: 69, companyId: 7, name: "Opto air" },
    { id: 70, companyId: 7, name: "First Line" },
    { id: 71, companyId: 7, name: "Zero Mega Soft" },
    { id: 72, companyId: 7, name: "Zero Soft" },
    { id: 73, companyId: 7, name: "Zero Medium" },
    { id: 74, companyId: 7, name: "Zero hard" },
    { id: 75, companyId: 7, name: "Retro Line" },
    { id: 76, companyId: 8, name: "Delta T" },
    { id: 77, companyId: 8, name: "Standard" },
    { id: 78, companyId: 8, name: "Super Soft" },
    { id: 79, companyId: 8, name: "ET" },
    { id: 80, companyId: 8, name: "Lunar" },
    { id: 81, companyId: 8, name: "Quantum" },
    { id: 82, companyId: 8, name: "Quantum Zero" },
    { id: 83, companyId: 8, name: "Sirius" },
    { id: 84, companyId: 9, name: "200 plastic" },
    { id: 85, companyId: 9, name: "300 plastic" },
    { id: 86, companyId: 9, name: "300 soft plastic" },
    { id: 87, companyId: 9, name: "350 soft plastic" },
    { id: 88, companyId: 9, name: "350 G plastic" },
    { id: 89, companyId: 9, name: "400 plastic" },
    { id: 90, companyId: 9, name: "Prodigy air plastic" },
    { id: 91, companyId: 9, name: "400 G plastic" },
    { id: 92, companyId: 9, name: "500 plastic" },
    { id: 93, companyId: 9, name: "750 plastic" },
    { id: 94, companyId: 9, name: "750 G plastic" },
    { id: 95, companyId: 10, name: "Tournament" },
    { id: 96, companyId: 10, name: "Vip" },
    { id: 97, companyId: 10, name: "Vip air" },
    { id: 98, companyId: 10, name: "Tournament Moori" },
    { id: 99, companyId: 10, name: "Mega Soft" },
    { id: 100, companyId: 10, name: "BT Soft" },
    { id: 101, companyId: 10, name: "BT Medium" },
    { id: 102, companyId: 10, name: "BT Hard" },
    { id: 103, companyId: 10, name: "Origio" },
    { id: 104, companyId: 11, name: "Icon" },
    { id: 105, companyId: 11, name: "Pinnacle" },
    { id: 106, companyId: 11, name: "Skyline" },
    { id: 107, companyId: 11, name: "Protege" },
    { id: 108, companyId: 11, name: "Gravity" },
    { id: 109, companyId: 11, name: "Excel" },
    { id: 110, companyId: 11, name: "Honey Bee" },
    { id: 111, companyId: 12, name: "K1 line" },
    { id: 112, companyId: 12, name: "K1 Soft" },
    { id: 113, companyId: 12, name: "K3 Line" },
    { id: 114, companyId: 12, name: "K3 Hard" },
    { id: 115, companyId: 12, name: "K1 glow-line" },
    { id: 116, companyId: 13, name: "Ultrium" },
    { id: 117, companyId: 13, name: "Basic" },
    { id: 118, companyId: 13, name: "Premium" },
    { id: 119, companyId: 14, name: "Sp line" },
    { id: 120, companyId: 14, name: "Pro line" },
    { id: 121, companyId: 14, name: "D-line" },
    { id: 122, companyId: 14, name: "Signature line" },
    { id: 123, companyId: 14, name: "Ev 7" },
    { id: 124, companyId: 14, name: "OG blend" },
    { id: 125, companyId: 15, name: "Neutron" },
    { id: 126, companyId: 15, name: "Cosmic neutron" },
    { id: 127, companyId: 15, name: "Protron" },
    { id: 128, companyId: 15, name: "Plasma" },
    { id: 129, companyId: 15, name: "Eclipse" },
    { id: 130, companyId: 15, name: "Eclipse Zero glow" },
    { id: 131, companyId: 15, name: "Fission" },
    { id: 132, companyId: 15, name: "Neutron core" },
    { id: 133, companyId: 15, name: "Electron" },
    { id: 134, companyId: 15, name: "Eco recycled" },
    { id: 135, companyId: 15, name: "Cosmic electron" },
]